spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: "jdbc:postgresql://localhost:5432/demo"
    username: postgres
    password: password

server:
  port: 8080

  # show error message when throwing error
  error:
    include-message: always
    include-binding-errors: always

application:
  # configuring external calls
  webclient:
    read-timeout: 30000
    connect-timeout: 30000