
spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:file:./src/main/resources/h2data/database
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

server:
  port: 8080

  # show error message when throwing error
  error:
    include-message: always
    include-binding-errors: always

application:
  # configuring external calls
  webclient:
    read-timeout: 30000
    connect-timeout: 30000