
spring:
  profiles:
    active: @spring.profiles.active@
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: "jdbc:postgresql://localhost:5432/demo"
    username: postgres
    password: password

server:
  # all endpoints should begin with this path
  servlet:
    contextPath: /api/v1